# Crowdin Configuration for CRESP Documentation
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."

files:
  - source: /docs/**/*.md
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    
  - source: /src/pages/**/*.{js,jsx,ts,tsx}
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-pages/**/%original_file_name%
    
  - source: /src/components/**/*.{js,jsx,ts,tsx}
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-pages/components/**/%original_file_name%
    
  - source: /blog/**/*.{md,mdx}
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name% 